[project]
name = "GEDAI-DecisionHelperAPI"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pydecision>=4.7.7",
    "uvicorn>=0.35.0",
]
